aisstream:
  api_key: "23f01fb154ef06c103887b7518f1482bc4b0f25d"
area_of_interest: 
  bounding_boxes: 
    - [[-90, -180], [90, 180]]
kafka:
  brokers:
    - "localhost:19092"
ais:
  topics:
    raw:
    - "ais_streamio_reports_raw"
  message_types:
    - "BaseStationReport"
    - "MultiSlotBinaryMessage"
    - "ExtendedClassBPositionReport"
    - "SafetyBroadcastMessage"
    - "PositionReport"
    - "ShipStaticData"
    - "StandardClassBPositionReport"
    - "StandardSearchAndRescueAircraftReport"
    - "StaticDataReport"
    - "SingleSlotBinaryMessage"
    - "Interrogation"
    - "LongRangeAisBroadcastMessage"
    - "GnssBroadcastBinaryMessage"
    - "DataLinkManagementMessage"
    - "AddressedSafetyMessage"
    - "AddressedBinaryMessage"
    - "CoordinatedUTCInquiry"
    - "BinaryAcknowledge"
    - "ChannelManagement"
    - "AssignedModeCommand"
    - "AidsToNavigationReport"
