name: osint

networks:
  kafka_network:
    driver: bridge

volumes:
  redpanda: null

services:
  redpanda:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --advertise-rpc-addr redpanda:33145
      - --rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.2
    container_name: redpanda
    volumes:
      - redpanda:/var/lib/redpanda/data
    networks:
      - kafka_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    restart: always

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.7.1
    networks:
      - kafka_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda
    restart: always

  osint-maritime-streamio:
    env_file:
      - .env
    build:
      context: ./maritime_streamio
      dockerfile: Dockerfile
    container_name: osint-maritime-streamio
    image: osint-maritime-streamio:latest
    ports:
      - "8001:8000"
    networks:
      - kafka_network
    depends_on:
      - redpanda
    restart: always

  # osint-maritime-streamio-processor:
  #   env_file:
  #     - .env
  #   build:
  #     context: ./maritime-streamio-processor
  #     dockerfile: Dockerfile
  #   container_name: osint-maritime-streamio_processor
  #   image: osint-maritime-streamio-processor:latest
  #   networks:
  #     - kafka_network
  #   depends_on:
  #     - redpanda
  #   restart: always
