kafka:
  broker: redpanda:9092
  topic: raw_maritime_streamio
  max_message_size: 1000000  # 1MB in bytes
ais:
  streamio:
    url: wss://stream.aisstream.io/v0/stream
  bounding_boxes:
    - [[-90, -180], [90, 180]]
buffer:
  flush_interval: 0.250
  max_size: 1000
websocket:
  reconnect_delay: 5
  max_reconnect_attempts: 10
metrics:
  log_interval: 60