kafka:
  broker: 
  - 'localhost:19092'
ais:
  topics:
    raw:
    - "raw_ais_reports"
    output:
    - "maritime_reports_test"
  position_message_types:
      - "ExtendedClassBPositionReport"
      - "PositionReport"
      - "StandardClassBPositionReport"
  message_types:
    - "BaseStationReport"
    - "MultiSlotBinaryMessage"
    - "ExtendedClassBPositionReport"
    - "SafetyBroadcastMessage"
    - "PositionReport"
    - "ShipStaticData"
    - "StandardClassBPositionReport"
    - "StandardSearchAndRescueAircraftReport"
    - "StaticDataReport"
    - "SingleSlotBinaryMessage"
    - "Interrogation"
    - "LongRangeAisBroadcastMessage"
    - "GnssBroadcastBinaryMessage"
    - "DataLinkManagementMessage"
    - "AddressedSafetyMessage"
    - "AddressedBinaryMessage"
    - "CoordinatedUTCInquiry"
    - "BinaryAcknowledge"
    - "ChannelManagement"
    - "AssignedModeCommand"
    - "AidsToNavigationReport"
